with open('combos_source.def', 'r') as file:
    data = file.readlines()

data.insert(0, "// This file is automatically generated by generate_combos.py.\n")
data.insert(1, "// Do not modify it; instead, modify combos_source.def and run generate_combos.py to generate combos.def.\n")

newData = []

for i in range(0, len(data)):
    newData.insert(i, data[i].replace("COMB_U(", "COMB(combo" + str(i) + ", "))

print("".join(newData))